# @package data
_target_dataset_name: "goldberg"

dataset_path: "data_preprocessing/datasets/goldberg/all_groups.csv"

abundance_h5_path: "huggingface_datasets/Goldberg/processed/abundance_data/abundance.h5"

hugging_face:
  dataset_name: "Goldberg"
  csv_filename: "all_groups_balanced.csv"
